# This is a basic workflow to help you get started with Actions

name: build-sphinx-to-gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: "docs/buildsite.sh"
        shell: bash
